Feature/wtm 462/implement save avatar on frontend
webtimemachine/wtm2 pull request #466
Opened 2024-10-01 12:09 UTC by aferrentinointermedia

### Issue: #462 

### 📑 Changes:

- Save avatar on frontend

### ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2024-10-01 15:06 UTC, dcoscolla-intermedia requested changes

2024-10-01 15:06 UTC, dcoscolla-intermedia commented on apps/extension/src/screens/profile.screen.tsx
> +    console.log(images);
This can be moved out of the component and console logs can be removed

2024-10-01 15:06 UTC, dcoscolla-intermedia commented on apps/webpage/src/app/profile/page.tsx
>      ];
This can be moved out of the component too

2024-10-07 19:44 UTC, jmartel07 approved these changes

2024-10-07 19:46 UTC, dcoscolla-intermedia approved these changes

2024-10-07 19:47 UTC, merged